[project]
name = "stat-app"
version = "0.1.0"
description = "Causal DAG Analysis for COVID-19 Vaccine Impact Study"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "lifelines>=0.30.3",
    "matplotlib>=3.10.9",
    "networkx>=3.6.1",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pandas-stubs>=3.0.0.260204",
    "scikit-learn>=1.8.0",
    "statsmodels>=0.14.6",
    "tableone>=0.9.6",
    "tabulate>=0.10.0",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "pytest==8.0.0",
]
